experiment_name: ablation
model_dir: ./training_result/ablation/train1/logs
summary_dir: ./training_result/ablation/train1/summaries
batch_size: 1
lr: 3e-5
epochs: 5
epochs_til_checkpoint: 1
steps_til_summary: 10
model_type: sine
latent_dim_shape: 300
latent_dim_expression: 100
hidden_num: 256
num_hidden_layers: 3
hyper_hidden_layers: 1

checkpoint_path: ./ckpt/model_epoch_0400.pth


